@echo off
echo Démarrage du serveur de développement Chrono-Carto...
echo.
echo 1. Arrêt des processus Node.js existants...
taskkill /f /im node.exe 2>nul
echo.
echo 2. Nettoyage du cache Next.js...
if exist .next rmdir /s /q .next
echo.
echo 3. Installation des dépendances...
npm install
echo.
echo 4. Démarrage du serveur...
npm run dev
pause
